name: mlflow-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - mlflow==2.12.1
      - scikit-learn==1.4.2
      - pandas==2.2.2
      - numpy==1.26.4
      - joblib==1.4.0
