name: CI Workflow MLflow Advance

on:
  push:
    paths:
      - MLProject/**
      - .github/workflows/ci.yml
      - Dockerfile
      - requirements.txt

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: mlflow-env
        environment-file: MLProject/conda.yaml
        auto-activate-base: false
        use-mamba: false

    - name: Verify Conda Environment
      shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: Install MLflow
      shell: bash -l {0}
      run: pip install mlflow

    - name: Run MLflow Project
      shell: bash -l {0}
      run: |
        cd MLProject
        mlflow run . -P data_path=dataset_preprocessed/online_shoppers_intention_preprocessed.csv --env-manager=local

    - name: Upload Model Artifact
      uses: actions/upload-artifact@v4
      with:
        name: best_model
        path: MLProject/outputs/best_model.pkl

    - name: DockerHub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      shell: bash -l {0}
      run: |
        cd MLProject
        LAST_RUN_ID=$(mlflow experiments list | awk 'NR==2 {print $1}' | xargs -I {} mlflow runs list --experiment-id {} | awk 'NR==2 {print $1}')
        echo "Last run ID: $LAST_RUN_ID"
        mlflow models build-docker -m mlruns/0/$LAST_RUN_ID/artifacts/mlflow_model -n msml_model_image
        docker tag msml_model_image ${{ secrets.DOCKERHUB_USERNAME }}/msml_model_image:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/msml_model_image:latest
